#!/bin/bash
#
# Get the samples from the VCF file

usage(){
    cat <<-EOM
        Usage: get_samples vcf_file
        
        gets the list of samples line seperated
EOM
}
if [[ $# -ne 1 ]];
then
    usage
    exit 1
fi
echo "#get_samples" $1
cat $1 | grep "#C" | cut -d $'\t' -f 10- | tr  $'\t' '\n' 
