#!/usr/bin/env python
#
# Take a tab-delimited file and attempts
# To convert it to a VCF file
#

import argsparse

MINIMAL_HEADER="""

"""

def vcf_to_tab(tab_file):
    with open(tab_file) as f:
        for line in f:

def main():
    parser = argsparse.ArgumentParser("Converts tab to VCF")
    parse.add_argument("tab_file",help="Tab delimited File")
    args = parser.parse_args()
    vcf_to_tab(args.tab_file)

if __name__=="__main__":
    main()
